language: node_js
node_js:
- '5.2'
before_script:
- npm install -g ava
deploy:
  provider: npm
  email: tusharmath@gmail.com
  on:
    branch: master
  api_key:
    secure: RuqMjA5/lwgbEQnyjl5sZPkwCGrDu7Z14gITyAcQbKXiZK70kU2gZoZ70y11hy7dE3Xe1BX8v+fFicQNafp1VjskA/g2VAprXp20E0ka4SArFufJC21IRR4yUzZ3X+piocWHSqJ7D8GCkEi7wpyzLSVIG3fu4UtY5O9UWPuhGLWR1svXVF56LYVMBlTdz63Ab2eX6VI+h/JE8V1SkkKoTew0F69mOwHNLBpFAUgQKPEm/iJiE/DDw33NGSxw5/gnewOhrl2s7ObSNIqViSPoC7g8qpGy4YUWWz7fu9Ee+oFejR+9Y8GJG/Gy759JQLRT4TmI6zFxgWlupPJFKtxwnYhNyD4HoJXl4d0lx1Rx/6uIqaImsoOGkFr6x7BKBOBHHu9ECMiw2NljhBGYEpJM23A9QtVZSeM8yMgpulQnYPPvn1Haju5yUQybu7Bo3XkRHCLtQmskQimeIw4bDeozhoPDRNPhqsjBkT9KY9tyjFWCE9/TmE9KriOrVBzSPmcs4jZfxbXUWlfmoBU3+VWBwnl0PAd8rtyccPeW7MT9J2PmyyRuUuGuepOVYEHd8BqgCKijTco3RkDI8sE+XVxlwUfUwdeLA9WKh3QrCMqbWWarCmpv1sKRfe9kQMn2ORWPJIO6D5i7Oqg0OF4eloOG6rbBgOuxXC/qLaJKKi2rZCE=
